### ISSUE TITLE
Error running under Windows

### ISSUE THREAD

**Issue by ltsj** [ByteDream/crunchyroll-go#31]
when i run under windows

`crunchy download -o "daaaaaaaaaaaaaaaarling.mkv" --audio ja-JP --subtitle ja-JP https://beta.crunchyroll.com/series/GY8VEQ95Y/darling-in-the-franxx -v -g 32 -p http://127.0.0.1:7890`

it will error like this
```
[debug] Executing `download` command with 1 arg(s)
[info] Using custom proxy http://127.0.0.1:7890
[debug] Validating arguments
[debug] Custom file ending '.mkv' (ffmpeg is installed)
[debug] Locales: audio: ja-JP / subtitle: ja-JP
[debug] Using resolution 'best'
[debug] Logging in
[err] zh-CN is not a supported locale, using en-US as fallback
[debug] Logged in
[debug] Parsing url 1
[err] interface conversion: interface {} is nil, not []interface {}: goroutine 1 [running]:
runtime/debug.Stack()
        /usr/lib/go/src/runtime/debug/stack.go:24 +0x65
github.com/ByteDream/crunchyroll-go/v2/cmd/crunchyroll-go/cmd.Execute.func1()
        /home/bytedream/backup/crunchyroll-go/cmd/crunchyroll-go/cmd/root.go:65 +0x4a
panic({0x1384a60, 0xc000243890})
        /usr/lib/go/src/runtime/panic.go:838 +0x207
github.com/ByteDream/crunchyroll-go/v2.(*Series).Seasons(0xc00035a3c0)
        /home/bytedream/backup/crunchyroll-go/video.go:217 +0x6c5
github.com/ByteDream/crunchyroll-go/v2.(*Crunchyroll).ExtractEpisodesFromUrl(0xc000016140?, {0xc000016140?, 0x1481d44?}, {0xc00007d8f8, 0x2, 0x0?})
        /home/bytedream/backup/crunchyroll-go/url.go:18 +0xb2
github.com/ByteDream/crunchyroll-go/v2/cmd/crunchyroll-go/cmd.extractEpisodes({0xc000016140, 0x43}, {0xc00007d8f8, 0x2, 0x2})
        /home/bytedream/backup/crunchyroll-go/cmd/crunchyroll-go/cmd/utils.go:261 +0x1cb
github.com/ByteDream/crunchyroll-go/v2/cmd/crunchyroll-go/cmd.downloadExtractEpisodes({0xc000016140?, 0x13db595?})
        /home/bytedream/backup/crunchyroll-go/cmd/crunchyroll-go/cmd/download.go:272 +0x91
github.com/ByteDream/crunchyroll-go/v2/cmd/crunchyroll-go/cmd.download({0xc00013c240?, 0x1, 0x0?})
        /home/bytedream/backup/crunchyroll-go/cmd/crunchyroll-go/cmd/download.go:132 +0xfd
github.com/ByteDream/crunchyroll-go/v2/cmd/crunchyroll-go/cmd.glob..func4(0x16a4f80?, {0xc00013c240, 0x1, 0xc})
        /home/bytedream/backup/crunchyroll-go/cmd/crunchyroll-go/cmd/download.go:74 +0x3c
github.com/spf13/cobra.(*Command).execute(0x16a4f80, {0xc00013c180, 0xc, 0xc})
        /home/bytedream/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x16a4a80)
        /home/bytedream/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /home/bytedream/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/ByteDream/crunchyroll-go/v2/cmd/crunchyroll-go/cmd.Execute()
        /home/bytedream/backup/crunchyroll-go/cmd/crunchyroll-go/cmd/root.go:72 +0x54
main.main()
        /home/bytedream/backup/crunchyroll-go/cmd/crunchyroll-go/main.go:8 +0x17
```
I hope to get help and thanks for your project~  ~In addition, is it possible to add a parameter to download the latest episodes?~

**Comment by ByteDream** [comment]
Does the same error happen when you change the subtitle language to `en-US`?

**Comment by ltsj** [comment]
i tried
 `crunchy download -o "daaaaaaaaaaaaaaaarling.mkv" --audio ja-JP --subtitle en-US https://beta.crunchyroll.com/series/GY8VEQ95Y/darling-in-the-franxx -v -g 32 -p http://127.0.0.1:7890` 
 `crunchy archive -o "{series_name}S{season_number}E{episode_number}.mkv" -l ja-JP https://beta.crunchyroll.com/series/GRJ0J828Y/kaguya-sama-love-is-war[S2E1-S2E2] -v -g 32 -p http://127.0.0.1:7890` 
but it didn't work and same error，I'm wondering if it has something to do with my proxy? But I can login with proxy，Also my system language is Chinese.

**Comment by ltsj** [comment]
Seems to be a proxy issue, it's the same when I'm on a Debian system and using through a proxy.

**Comment by ByteDream** [comment]
Do you have a proxy with which you can check it again?

**Comment by ltsj** [comment]
> 您是否有代理可以再次检查它？

Thanks! When I turned on the proxy software, I did not use the parameter -p http://127.0.0.1:7890, and switched to another proxy node, it worked, I don't know what happened, maybe crunchyroll limited my acting....

**Comment by ByteDream** [comment]
A parameter to download the latest episode would be an idea for [v3](https://github.com/users/ByteDream/projects/1).
